# frozen_string_literal: true

require "minitest/autorun"
require_relative "../lib/pura-webp"

# Pixel-accuracy tests: compares pura-webp decode output against
# reference PPMs generated by a reference decoder (libwebp via sips).
#
# Tolerance accounts for the loop filter not yet being implemented —
# without it, block boundaries show small steps (usually <8/channel).
# When the loop filter lands, tolerance should drop to ~2.
class TestDecoderAccuracy < Minitest::Test
  FIXTURE_DIR = File.join(__dir__, "fixtures")

  MAE_TOLERANCE = 8.0       # mean absolute error per channel
  MAX_DIFF_TOLERANCE = 40   # allow a few outlier pixels (loop-filter-sensitive)

  def load_ppm(path)
    data = File.binread(path)
    raise "not P6" unless data.start_with?("P6")

    lines = []
    pos = 0
    while lines.size < 3
      nl = data.index("\n", pos)
      line = data.byteslice(pos, nl - pos)
      pos = nl + 1
      lines << line unless line.start_with?("#")
    end
    _w, _h = lines[1].split.map(&:to_i)
    { pixels: data.byteslice(pos, data.bytesize - pos) }
  end

  def compare(decoded_pixels, reference_pixels)
    raise "size mismatch" if decoded_pixels.bytesize != reference_pixels.bytesize

    diffs = decoded_pixels.bytesize.times.map do |i|
      (decoded_pixels.getbyte(i) - reference_pixels.getbyte(i)).abs
    end
    mae = diffs.sum.to_f / diffs.size
    max = diffs.max
    [mae, max]
  end

  def test_16x16_pixel_accuracy
    image = Pura::Webp.decode(File.join(FIXTURE_DIR, "test_16x16.webp"))
    ref = load_ppm(File.join(FIXTURE_DIR, "test_16x16.ppm"))
    mae, max_diff = compare(image.pixels, ref[:pixels])

    assert_operator mae, :<=, MAE_TOLERANCE,
                    "MAE=#{mae.round(2)} exceeds tolerance (max_diff=#{max_diff})"
    assert_operator max_diff, :<=, MAX_DIFF_TOLERANCE,
                    "max diff=#{max_diff} exceeds tolerance (MAE=#{mae.round(2)})"
  end

  def test_64x64_pixel_accuracy
    image = Pura::Webp.decode(File.join(FIXTURE_DIR, "test_64x64.webp"))
    ref = load_ppm(File.join(FIXTURE_DIR, "test_64x64.ppm"))
    mae, max_diff = compare(image.pixels, ref[:pixels])

    assert_operator mae, :<=, MAE_TOLERANCE,
                    "MAE=#{mae.round(2)} exceeds tolerance (max_diff=#{max_diff})"
    assert_operator max_diff, :<=, MAX_DIFF_TOLERANCE,
                    "max diff=#{max_diff} exceeds tolerance (MAE=#{mae.round(2)})"
  end
end
