AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 100
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Max: 200
  Exclude:
    - "test/**/*"

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 30

Metrics/ClassLength:
  Max: 800

Metrics/BlockLength:
  Max: 50
  Exclude:
    - "test/**/*"
    - "*.gemspec"

Metrics/ParameterLists:
  Max: 12

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y
    - w
    - h
    - r
    - g
    - b
    - u
    - v
    - n
    - io
    - bx
    - by
    - bd

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/pura-*.rb"

Naming/VariableNumber:
  Enabled: false

Metrics/BlockNesting:
  Max: 5

Naming/MethodParameterName:
  Enabled: false

Metrics/ModuleLength:
  Max: 500

Naming/PredicateMethod:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/UselessConstantScoping:
  Enabled: false
